# 4.2 Universal Functions: Fast Element-Wise Array Functions（通用函数：快速点对点数组函数）

universal function, 或 ufunc, 是用来在ndarray中实现element-wise操作的。

可以认为这个ufunc可以把一些简单的函数做快速的向量化封装，输入是一个以上的标量，输出也是一个以上的标量。

很多ufuncs都是点对点的变换，像sqrt或exp：

In [76]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [78]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

这些函数叫做一元通用函数（unary ufuncs）。其他一些函数，比如add或maximum，需要两个数组（binary ufuncs）,并返回一个数组作为结果：

In [79]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.06327671, -0.79625631, -0.93831331,  0.80942918, -0.40459487,
       -0.62894547, -0.6221986 ,  0.21423106])

In [80]:
y

array([-0.6363266 , -0.75177805, -0.0191014 , -1.99955493, -0.23259148,
        0.36255693,  0.6617483 ,  1.89638906])

In [81]:
np.maximum(x, y)

array([ 0.06327671, -0.75177805, -0.0191014 ,  0.80942918, -0.23259148,
        0.36255693,  0.6617483 ,  1.89638906])

这里mamimum点对点的比较x和y中的元素。

尽管不常见，但ufunc也能返回多个数组。例如modf，这是一个向量版的divmod（python内建函数），modf会返回小数部分和整数部分：

>本函数是实现a除以b，然后返回商与余数的元组。如果两个参数a,b都是整数，那么会采用整数除法，结果相当于（a//b, a % b)。如果a或b是浮点数，相当于（math.floor(a/b), a%b)。

In [90]:
arr = np.random.randn(7) * 5
arr

array([ -0.62515846,  -2.08128899,   1.66210274,   1.35871674,
        -1.12432188,   5.36335202,  11.20860241])

In [91]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.62515846, -0.08128899,  0.66210274,  0.35871674, -0.12432188,
        0.36335202,  0.20860241])

In [92]:
whole_part

array([ -0.,  -2.,   1.,   1.,  -1.,   5.,  11.])

ufunc能接受一个可选参数作为输出，这样可以直接更改原有的数组：

In [93]:
arr

array([ -0.62515846,  -2.08128899,   1.66210274,   1.35871674,
        -1.12432188,   5.36335202,  11.20860241])

In [94]:
np.sqrt(arr) # 没有改变原有的arr

E:\TLT\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,         nan,  1.28922564,  1.16564005,         nan,
        2.31589119,  3.34792509])

In [95]:
arr

array([ -0.62515846,  -2.08128899,   1.66210274,   1.35871674,
        -1.12432188,   5.36335202,  11.20860241])

In [97]:
np.sqrt(arr, arr) # 改变了原有的arr

E:\TLT\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,         nan,  1.28922564,  1.16564005,         nan,
        2.31589119,  3.34792509])

In [98]:
arr

array([        nan,         nan,  1.28922564,  1.16564005,         nan,
        2.31589119,  3.34792509])

一些一元通用函数：

![](../MarkdownPhotos/chp04/屏幕快照 2017-10-25 下午1.19.41.png)



一些二元通用函数：
![](../MarkdownPhotos/chp04/屏幕快照 2017-10-25 下午1.21.08.png)

![](../MarkdownPhotos/chp04/屏幕快照 2017-10-25 下午1.21.42.png)



In [104]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [100]:
np.eye(3,k=1)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [105]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [103]:
np.arange(4).reshape(2,2)*np.arange(4).reshape(2,2)

array([[0, 1],
       [4, 9]])